name: test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  test_add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest tests/test_add.py

  test_capitalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest tests/test_capitalize.py
